name: Update README

on:
  schedule:
    # Run once every hour
    - cron: '0 * * * *'  # Runs every hour at minute 0
  push:
    # Trigger the workflow when changes are pushed to the main branch
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version to use

  # Create package.json if it doesn't exist
    - name: Ensure package.json exists
      run: |
        if [ ! -f package.json ]; then
          echo '{}' > package.json
          npm init -y
        fi

    # Install dependencies (if any are listed in package.json)
    - name: Install dependencies
      run: npm install

    # Run the script to update the README
    - name: Update README
      run: node update-readme.js  # Your script to update the README file

    # Commit changes to the repository
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add card.svg current-frame.jpg frame-counter.txt
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Godfather frame $(cat frame-counter.txt || echo 'unknown')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
