name: Update README

on:
  schedule:
    # Run once a day at midnight UTC
    - cron: '0 0 * * *'  # Runs once per day at midnight UTC
  push:
    # Trigger the workflow when changes are pushed to the main branch
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version to use

    # Install dependencies (if using any libraries)
    - name: Install dependencies
      run: npm install  # if you have any dependencies in package.json

    # Run the script to update the README
    - name: Update README
      run: node update-readme.js  # Your script to update the README file

    # Commit changes to the repository
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with latest data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
